### PR TITLE
patch sent by Tomas Kalibera

### PR DESCRIPTION
**Pull request by edzer**

### CODE REVIEW

**Comment by edzer** [comment]
Thanks! Is it time to drop the CXX11 requirement?

**Comment by edzer** [comment]
Great, I will try without CXX11 on win-builder; @kalibera, do you have intel on cmake in rtools?

**Comment by kalibera** [comment]
> I think you might want to keep the existing Makevars.win and move the patch to Makevars.ucrt. That would apply the patch for R >4.2 but keep compatibility with R 4.0 and 4.1.

Yes, that is fine if you want to support R < 4.2.

**Comment by kalibera** [comment]
> Great, I will try without CXX11 on win-builder; @kalibera, do you have intel on cmake in rtools?

There is cmake in Rtools (that is, even cmake for native compilation). It is documented in "Building R* and packages on Windows", e.g. https://cran.r-project.org/bin/windows/base/howto-R-devel.html.

However, I would not recommend using it unless you are embedding sources of software that only supports cmake to build (and even there might be other option - contribute that software to MXE/Rtools, as it might be easier to use cmake during cross-compilation on Linux).

A number of libraries included in MXE/Rtools does not use the "modern" way to write cmake files that makes them relocatable. Also, often, the detection of other libraries (dependencies) in external software is broken. You could easily run to some problems with this. I've added some hot-fixes of generated cmake files (sometimes contributed externally), but surely there will be more problems. Of course you can debug them, identify, and fix for others.

**Comment by kalibera** [comment]
Abseil-cpp is in a recent update of Rtools43. See https://cran.r-project.org/bin/windows/Rtools/rtools43/news.html
(not yet in MXE).

**Comment by edzer** [comment]
Awaiting @paleolimbot 's refactoring, I released `s2` 1.1.7 with the only change, relative to 1.1.6, to merge this makefile and push CXX11 to CXX14 in Makevars.in. I did that locally, not on GitHub, to not destroy the refactoring.

**Pull request closed without merging**
